using System;
using SmallWorld.Save.Stage10;
namespace SmallWorld.Save.Stage12
{
 public enum MemorySpacePhase { WhiteRoom, Entering, Inside, Exiting }
 [Serializable] public sealed class MemorySpaceDefinition { public string Id=""; public string ReturnSceneId="02_RealityRoom"; public string EntrySceneId=""; public string SafeZoneId=""; public void Validate(){if(string.IsNullOrWhiteSpace(Id))throw new ArgumentException("기억 공간 ID가 필요합니다.");if(string.IsNullOrWhiteSpace(EntrySceneId))throw new ArgumentException("기억 공간 장면 ID가 필요합니다.");if(string.IsNullOrWhiteSpace(SafeZoneId))throw new ArgumentException("안전 구역 ID가 필요합니다.");} }
 [Serializable] public sealed class MemorySpaceState { public string SpaceId=""; public MemorySpacePhase Phase=MemorySpacePhase.WhiteRoom; public bool HasEntered; public bool HasExited; public bool SafeZoneReached; public int VisitCount; public int PuzzleProgress; public MemorySpaceState Clone()=>(MemorySpaceState)MemberwiseClone(); }
 public sealed class MemorySpaceProgress { const string Prefix="memory-space/"; public MemorySpaceState Get(SaveData save,string id){if(save==null)throw new ArgumentNullException(nameof(save));var e=save.SceneStates.Find(x=>x.SceneId==Prefix+id&&x.StateKey=="state");if(e==null)return new MemorySpaceState{SpaceId=id};var p=e.Value.Split('|');if(p.Length!=6)return new MemorySpaceState{SpaceId=id};return new MemorySpaceState{SpaceId=id,Phase=(MemorySpacePhase)P(p[0]),HasEntered=P(p[1])!=0,HasExited=P(p[2])!=0,SafeZoneReached=P(p[3])!=0,VisitCount=P(p[4]),PuzzleProgress=P(p[5])};} public void Set(SaveData save,MemorySpaceState s){if(save==null)throw new ArgumentNullException(nameof(save));if(s==null||string.IsNullOrWhiteSpace(s.SpaceId))throw new ArgumentException("기억 공간 상태가 유효하지 않습니다.");var e=save.SceneStates.Find(x=>x.SceneId==Prefix+s.SpaceId&&x.StateKey=="state");if(e==null){e=new SceneStateSaveEntry{SceneId=Prefix+s.SpaceId,StateKey="state"};save.SceneStates.Add(e);}e.Value=string.Join("|",(int)s.Phase,s.HasEntered?1:0,s.HasExited?1:0,s.SafeZoneReached?1:0,s.VisitCount,s.PuzzleProgress);}static int P(string v)=>int.TryParse(v,out var n)?n:0; }
 public sealed class MemorySpaceFlow { public MemorySpaceState Enter(MemorySpaceDefinition d,MemorySpaceState s){d.Validate();if(s==null)s=new MemorySpaceState{SpaceId=d.Id};if(s.SpaceId!=d.Id)throw new InvalidOperationException("기억 공간 상태 ID가 일치하지 않습니다.");if(s.Phase==MemorySpacePhase.Inside)return s;s.Phase=MemorySpacePhase.Inside;s.HasEntered=true;s.HasExited=false;s.VisitCount++;return s;} public MemorySpaceState Exit(MemorySpaceDefinition d,MemorySpaceState s){d.Validate();if(s==null||s.SpaceId!=d.Id||!s.HasEntered)throw new InvalidOperationException("입장하지 않은 기억 공간은 탈출할 수 없습니다.");s.Phase=MemorySpacePhase.WhiteRoom;s.HasExited=true;return s;} public void ReachSafeZone(MemorySpaceDefinition d,MemorySpaceState s){d.Validate();if(s==null||s.Phase!=MemorySpacePhase.Inside)throw new InvalidOperationException("기억 공간 안에서만 안전 구역에 도달할 수 있습니다.");s.SafeZoneReached=true;} }
}
